### PR TITLE
Favicon variation

### PR DESCRIPTION
**Pull request by maceq687**
Created based on the deranged logo
favic
Perhaps the light gradient from the top might be too much 🤔

### CODE REVIEW

**Comment by hypesystem** [comment]
Hmm.. can we do it with no background on it at all?

... and maybe we could do it in black/white depending on browser color scheme, c.f. https://phuoc.ng/collection/html-dom/change-the-favicon-dynamically-based-on-user-color-scheme-preference/#changing-favicon-dynamically-using-html-link-tags

**Comment by maceq687** [comment]
> Hmm.. can we do it with no background on it at all?

So just the 'd' with no circle?

> ... and maybe we could do it in black/white depending on browser color scheme

Sure!

**Comment by hypesystem** [comment]
Yes :smile:

**Comment by maceq687** [comment]
New light and dark friendly b&w favicons:
dark-favic
light-favic

Might be worth noting that it **follows device color mode, not browser color mode**
(i.e. if you happen to have your OS set to dark mode but your browser is not following system schema then it might not look great)

**Review by hypesystem — APPROVED** [review]
Great!

**Pull request merged**
