### PR TITLE
Nornorm case

### PR DESCRIPTION
**Pull request by hypesystem**
Screenshot 2022-07-01 at 13-57-49 Cases ____ deranged

### CODE REVIEW

**Comment by hypesystem** [comment]
@Arth101 preview link: https://deploy-preview-38--zealous-fermat-77bc7b.netlify.app/cases/

**Review by Arth101 — COMMENTED** [review]
Looks good :). Jeg har spurgt ind til feedback fra K&M og vi burde få en quote i næste uge fra dem.

**Comment by haid0109** [comment]
> Looks good :). Jeg har spurgt ind til feedback fra K&M og vi burde få en quote i næste uge fra dem.

@Arth101 er der kommet svar fra K&M?

**Comment by hypesystem** [comment]
@Arth101 status, noget nyt her?

**Comment by Arth101** [comment]
> @Arth101 status, noget nyt her?

Sorry ikke endnu. Jeg får lige skrevet en mail, da min NORNOM slack access er blevet fjernet. Onnit!

**Comment by Arth101** [comment]
Der er kommet en quote fra K&M:

> deranged provided our team with competent frontend and backend development ressources and helped us deliver solutions that fit our client’s needs. With a fast onboarding, they were quickly adding value across feature development, testing and client communication. I really appreciate their adaptability and scalability, which allowed us to deliver the fluctuating level of development bandwidth that the client requested.

**Review by Arth101 — APPROVED** [review]

**Pull request merged**
