### PR TITLE
First version of anonymized nasdaq listed scaleup case

### PR DESCRIPTION
**Pull request by hypesystem**
image

### CODE REVIEW

**Comment by haid0109** [comment]
This tech scaleup case is probably the most interesting case/the one that would draw the most attention from clients, therefore I think we should put it at the top.

**Review by haid0109 — COMMENTED** [review]
all looks good, just a little comment.

**Comment by hypesystem** [comment]
That's true, if we are looking for similar clients where we can do coaching, for sure :smile: willfix

**Comment by hypesystem** [comment]
Hmm, might move it to 2nd place, just so we have a named customer first, so it doesn't seem like everyone is just anonymous :smile:

**Pull request merged**
