### PR TITLE
Updated who we are page

### PR DESCRIPTION
**Pull request by itami187**
Added three more people to the list using html and reusing the existing css format to fit the design of the page

Screenshot from 2020-11-20 15-17-26
Screenshot from 2020-11-20 15-17-54
Screenshot from 2020-11-20 15-17-58
Screenshot from 2020-11-20 15-18-07
Screenshot from 2020-11-20 15-18-11
Screenshot from 2020-11-20 15-18-41
Screenshot from 2020-11-20 15-19-18
Screenshot from 2020-11-20 15-19-20

.

### CODE REVIEW

**Comment by hypesystem** [comment]
Live preview her: https://deploy-preview-26--zealous-fermat-77bc7b.netlify.app/who-we-are/

I dit screenshot ser det ud til at der mangler alle skrifttyperne? Det er underligt!

Derudover ligner det at du ikke har fået committed selve billederne op?

image

**Comment by hypesystem** [comment]
Hov, opdaterede lige live preview linket til et bedre et der opdaterer når du laver nyt her i PRet: https://deploy-preview-26--zealous-fermat-77bc7b.netlify.app/who-we-are/

Nu er billederne der, men de er meget store i filstørrelse. Jeg nævnte i opgavebeskrivelsen at du kunne resize og compresse med squoosh.app - tjek størrelsen på de andre billeder, og lav gerne de her om til noget lignende. Læg også mærke til at der findes både `niels-abildgaard.jpg` og `niels-abildgaard-thumb.jpg`. Vi vil gerne have at de nye billeder findes i samme format :smile:

**Comment by hypesystem** [comment]
Jeg synes det bliver lidt kedeligt i breakpoint sm hvor alle 3 nye billeder viser tekst til højre side. Én af dem burde være anderledes for at breake det lidt op.

Screenshot_2020-11-23 the Team ↳↷↷ deranged

Det ser rigtig godt ud med de andre breakpoints :+1:

**Comment by hypesystem** [comment]
(Og kodemæssigt er det også fint!)

**Comment by hypesystem** [comment]
Billederne i fuld størrelse (dem uden `-thumb` i navnet) er stadig meget store (over 2 mb hver). De skal også lige resizes (jf. størrelsen på de andre billeder).

Når det er gjort tror jeg sgu vi er klar til at få nogle tekster på og udgive?

Måske @Josefineolder vil kigge på tekster?

**Comment by hypesystem** [comment]
Looks good to me!

@Josefineolder Haidar's title is "Student." and Alexandra's is "Student" (no period). I feel like this should be consistent.

Maybe someone else wants to give feedback, too, before we merge? @Arth101 @itviking @HelenaBach

**Comment by Josefineolder** [comment]
@hypesystem that's been changed

**Comment by Arth101** [comment]
Not really related specific to this PR but it does seem weird that only some of employees has their degree (fx. BSc Computer Science) written next to "software developer". I think everyone's education should be shown, or no ones. Also I think we should move the images around, since Asbjørn and Niels creates some kind of strange symmetry because of their very similar hand placement.

Otherwise I think it looks pretty awesome. Good job everyone :).

**Comment by hypesystem** [comment]
Ah yes, I think we should add "BSc Software Development" to Liv, and "BA Web Development" to Anders.

At the same time, we should update Niels Christensen's title to "MSc Software Development".

I don't know if @ITViking has a formal title we should put on here?

Additionally, I think we should update the "Software developer" text to be our formal company titles:
- Staff Software Developer for me and Asbjørn
- Senior Software Developer for Anders and Niels Christensen
- Software Developer for Philip, Helena and Liv
- Trainee Software Developer for Alexandra and Haidar

Will you update this, @itami187 ?

**Comment by hypesystem** [comment]
Also, let's move the order around as Anders suggested, but do this in another PR after this has been merged.

I think a good new order would be (taking into account who is here full time):
- me
- anders
- helena
- philip
- alexandra
- haidar
- asbjørn
- niels christensen
- liv

**Comment by itami187** [comment]
@hypesystem the new order of people displayed on the website is done. made a new PR for it as requested

**Comment by hypesystem** [comment]
Ok very small last thing! It looks like in your merge request you removed the last names of Anders and Haidar, which Josefine added in this commit: https://github.com/derangeddk/deranged.dk/pull/26/commits/e5ea730c3dcbf84bf430512af3711327af362117 -- please add them again :smile:

The last 4 commits you have break down like this: 3 commits with changes; then 1 merge commit. Confusingly, you have given the same commit message for all 3, which makes them hard to read!

Here are some hints that may help:

- If you have made a commit, then realize you need to add a little change to it, you can `git add` that change, then use `git commit --amend` to include the change in the latest commit (instead of making a new commit).
- When you have a merge commit that is ready to complete, if you simply `git commit` with no message, you will get a nice merge commit message instead, that makes it clear what is going on in the commit.

**Pull request merged**
